### ISSUE TITLE
Add delay when turning off Wifi when the screen is off

### ISSUE THREAD

**Issue by DevLuuk** [DevLuuk/SleepyWifi#14]

**Comment by DevLuuk** [comment]
Right now it is already implemented but it starts after 5 seconds. I can change that but I think that 30 minutes is very long.

**Comment by maverick74** [comment]
30 min was an example.

But please consider that one may want to keep wireless on a bit more to complete a download.

Would be nice if one could set it as one wish

**Comment by DevLuuk** [comment]
I have tried your request out in the app and it is creating a new problem. The new problem is that Android kills my app in the background if I add a sleep function in my code for the delay that you want.

**Comment by maverick74** [comment]
It doesn't have to be 30 min. That was just an example! It could be 5 min... Or 10...

It would be great, however, if it would allow the user to configure the desired amount of time.

**Comment by DevLuuk** [comment]
I have implemented the function on the feature branch. The problem is that the app sometimes crashes because Android doesn't like the async sleep thread that I use.

**Comment by DevLuuk** [comment]
@maverick74 Can you test out version 1.8 for me? The delay function doesn't always work on my phone.

**Comment by maverick74** [comment]
@DevLuuk 
will do so :)

**Comment by maverick74** [comment]
so far it seems to be working ok here... :)

thanks

**Comment by DevLuuk** [comment]
This function is still buggy with me. I have stashed my code in the feature/SleepTimer branch if you want to fix it.
