### ISSUE TITLE
Add option to let Wifi on when phone is plugged in.

### ISSUE THREAD

**Issue by DevLuuk** [DevLuuk/SleepyWifi#2]

**Comment by TPS** [comment]
@DevLuuk Is there hope that this might be added soon?  This would replicate _that_ previously-available OS option.

**Comment by DevLuuk** [comment]
Yes, next week I am going to add this feature

**Comment by DevLuuk** [comment]
This week I am going to try it again to add the function. The last time it didn't work as I wanted it to work.

**Comment by DevLuuk** [comment]
I am not going to work further on this function.

**Comment by TPS** [comment]
It's ok; I found that [WiFi Automatic (Turn off WiFi automatically)](https://f-droid.org/app/de.j4velin.wifiAutoOff) has it perfectly.
